/**
 * bcbs239-lakehouse dashboard data accessors.
 *
 * Reads from `lib/data/snapshot.json`, generated by
 * `scripts/export_dashboard_data.py` querying the Databricks SQL warehouse
 * (Free Edition) after `make refresh`. The snapshot is committed so Vercel
 * builds work without Databricks credentials.
 *
 * Re-export the snapshot:
 *   uv run python dashboard/scripts/export_dashboard_data.py
 */

import snapshotJson from "./data/snapshot.json";

// ── Types ─────────────────────────────────────────────────────────────

export type Layer = "bronze" | "silver" | "gold";

export type DqDimension =
  | "completeness"
  | "accuracy"
  | "timeliness"
  | "integrity";

export type DqSource = "counterparty" | "exposure" | "collateral";

export type DqScore = {
  source: DqSource;
  dimension: DqDimension;
  score: number; // [0, 1]
  sample_size: number;
  failed_count: number;
};

export type ScorecardSnapshot = {
  snapshot_ts: string;
  label: string;
  dimensions: DqScore[];
};

export type RwaRow = {
  lei: string;
  exposure_type: string;
  as_of_date: string;
  exposure_count: number;
  total_amount_eur: number;
  total_rwa_eur: number;
};

export type RowCounts = Record<Layer, Record<string, number>>;

export type Snapshot = {
  extracted_at: string;
  row_counts: RowCounts;
  scorecard_snapshots: ScorecardSnapshot[];
  rwa_top: RwaRow[];
  catalog: string;
  synthetic: true;
  synthetic_lei_prefix: string;
};

// ── Snapshot wiring ───────────────────────────────────────────────────

const SNAPSHOT = snapshotJson as Snapshot;

export const EXTRACTED_AT: string = SNAPSHOT.extracted_at;
export const CATALOG: string = SNAPSHOT.catalog;
export const ROW_COUNTS: RowCounts = SNAPSHOT.row_counts;
export const SCORECARD_SNAPSHOTS: ScorecardSnapshot[] =
  SNAPSHOT.scorecard_snapshots;
export const RWA_TOP: RwaRow[] = SNAPSHOT.rwa_top;

// ── Accessors ─────────────────────────────────────────────────────────

export function getLatestSnapshot(): ScorecardSnapshot | null {
  return SCORECARD_SNAPSHOTS.at(-1) ?? null;
}

export function getEarliestSnapshot(): ScorecardSnapshot | null {
  return SCORECARD_SNAPSHOTS.at(0) ?? null;
}

/** Average score across all (source, dimension) rows for a given snapshot. */
export function averageScore(snapshot: ScorecardSnapshot): number {
  if (snapshot.dimensions.length === 0) return 1;
  const total = snapshot.dimensions.reduce((acc, d) => acc + d.score, 0);
  return total / snapshot.dimensions.length;
}

/** Average score for a specific dimension (across all 3 sources). */
export function averageScoreByDimension(
  snapshot: ScorecardSnapshot,
  dimension: DqDimension,
): number {
  const matching = snapshot.dimensions.filter((d) => d.dimension === dimension);
  if (matching.length === 0) return 1;
  const total = matching.reduce((acc, d) => acc + d.score, 0);
  return total / matching.length;
}

/** Build a (source, dimension) -> score map for fast lookup in tables. */
export function indexBySourceDimension(
  snapshot: ScorecardSnapshot,
): Map<string, DqScore> {
  const out = new Map<string, DqScore>();
  for (const dim of snapshot.dimensions) {
    out.set(`${dim.source}.${dim.dimension}`, dim);
  }
  return out;
}

/** Pair the earliest + latest snapshots for a clean-vs-dirty comparison.
 *  Returns null when only one snapshot exists. */
export function getDriftPair(): {
  t1: ScorecardSnapshot;
  t2: ScorecardSnapshot;
} | null {
  if (SCORECARD_SNAPSHOTS.length < 2) return null;
  return {
    t1: SCORECARD_SNAPSHOTS[0],
    t2: SCORECARD_SNAPSHOTS.at(-1)!,
  };
}

export function formatEur(amount: number): string {
  if (amount >= 1e9) return `€${(amount / 1e9).toFixed(2)}B`;
  if (amount >= 1e6) return `€${(amount / 1e6).toFixed(1)}M`;
  if (amount >= 1e3) return `€${(amount / 1e3).toFixed(1)}K`;
  return `€${amount.toFixed(0)}`;
}

export function formatPct(score: number): string {
  return `${(score * 100).toFixed(1)}%`;
}

/** Score colour by severity — used for tile + table cell tinting. */
export type ScoreSeverity = "good" | "warn" | "bad";

export function severityFor(score: number): ScoreSeverity {
  if (score >= 0.95) return "good";
  if (score >= 0.8) return "warn";
  return "bad";
}
